/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Get analysis results with strategy-based scoring.
         *
         *     If no recent analysis exists or force_refresh is True, runs a new analysis.
         *     Otherwise returns the latest cached analysis.
         *
         *     Available strategies:
         *     - safe_steady: Low risk, prioritizes stable profits
         *     - balanced: Equal consideration of all factors
         *     - aggressive: High risk tolerance, prioritizes ROI and trends
         */
        get: operations["get_analysis_api_analysis_get"];
        put?: never;
        /**
         * Trigger Analysis
         * @description Trigger a new analysis run in the background.
         *
         *     Returns immediately with status, analysis runs asynchronously.
         */
        post: operations["trigger_analysis_api_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Status
         * @description Get current analysis status.
         */
        get: operations["get_analysis_status_api_analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Analysis Progress
         * @description Stream analysis progress via Server-Sent Events (SSE).
         *
         *     Returns real-time progress updates as the analysis runs.
         *     Connection stays open for live updates across continuous background polling
         *     until the client disconnects.
         */
        get: operations["stream_analysis_progress_api_analysis_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rescore Analysis
         * @description Rescore existing analysis data with a new strategy.
         *
         *     Does not fetch new data, just recalculates scores based on the selected strategy.
         *
         *     Available strategies:
         *     - safe_steady: Low risk, prioritizes stable profits
         *     - balanced: Equal consideration of all factors
         *     - aggressive: High risk tolerance, prioritizes ROI and trends
         */
        post: operations["rescore_analysis_api_analysis_rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Strategies
         * @description Get all available trading strategies.
         *
         *     Returns a list of strategy profiles with their configurations.
         */
        get: operations["get_strategies_api_analysis_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Get paginated list of historical market runs.
         */
        get: operations["get_history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Detail
         * @description Get detailed data for a specific market run.
         */
        get: operations["get_run_detail_api_history__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{run_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Analysis
         * @description Get full analysis data for a historical run.
         *
         *     Returns the complete scored analysis data that can be loaded
         *     into the Analysis tab for review.
         */
        get: operations["get_run_analysis_api_history__run_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sets
         * @description Get all Prime sets from database.
         */
        get: operations["get_sets_api_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Set Detail
         * @description Get detailed information for a specific set.
         */
        get: operations["get_set_detail_api_sets__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{slug}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Set History
         * @description Get price and profit history for a set.
         */
        get: operations["get_set_history_api_sets__slug__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Get database and analysis statistics.
         */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_api_stats_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Data
         * @description Export all market data.
         */
        get: operations["export_data_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export To File
         * @description Export data to a downloadable JSON file.
         */
        get: operations["export_to_file_api_export_file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Summary
         * @description Get a quick summary of exportable data.
         */
        get: operations["export_summary_api_export_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisConfig
         * @description Configuration for running analysis.
         */
        AnalysisConfig: {
            /** @default balanced */
            strategy: components["schemas"]["StrategyType"];
            /** @default instant */
            execution_mode: components["schemas"]["ExecutionMode"];
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
            /**
             * Profit Weight
             * @default 1
             */
            profit_weight: number;
            /**
             * Volume Weight
             * @default 1.2
             */
            volume_weight: number;
        };
        /**
         * AnalysisResponse
         * @description Response for analysis endpoints.
         */
        AnalysisResponse: {
            /** Run Id */
            run_id?: number | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Sets */
            sets: components["schemas"]["ScoredData"][];
            /** Total Sets */
            total_sets: number;
            /** Profitable Sets */
            profitable_sets: number;
            weights: components["schemas"]["WeightsConfig"];
            /** @default balanced */
            strategy: components["schemas"]["StrategyType"];
            /** @default instant */
            execution_mode: components["schemas"]["ExecutionMode"];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /**
         * AnalysisStartedResponse
         * @description Response when analysis is started in background.
         */
        AnalysisStartedResponse: {
            /** Message */
            message: string;
            /**
             * Status
             * @default started
             */
            status: string;
            /**
             * Estimated Time Seconds
             * @default 60
             */
            estimated_time_seconds: number;
        };
        /**
         * AnalysisStats
         * @description Analysis-related statistics.
         */
        AnalysisStats: {
            /** Cache Age Seconds */
            cache_age_seconds?: number | null;
            /** Last Analysis */
            last_analysis?: string | null;
            /** Total Prime Sets */
            total_prime_sets?: number | null;
        };
        /**
         * AnalysisStatusResponse
         * @description Response for analysis status check.
         */
        AnalysisStatusResponse: {
            /** Status */
            status: string;
            /** Progress */
            progress?: number | null;
            /** Message */
            message?: string | null;
            /** Run Id */
            run_id?: number | null;
        };
        /**
         * DatabaseStats
         * @description Database statistics.
         */
        DatabaseStats: {
            /** Total Runs */
            total_runs: number;
            /** Total Profit Records */
            total_profit_records: number;
            /** Database Size Bytes */
            database_size_bytes: number;
            /** First Run */
            first_run?: string | null;
            /** Last Run */
            last_run?: string | null;
            /** Time Span Days */
            time_span_days?: number | null;
        };
        /**
         * ExecutionMode
         * @description Execution assumptions for profit and scoring calculations.
         * @enum {string}
         */
        ExecutionMode: "instant" | "patient";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryResponse
         * @description Response for history list endpoint.
         */
        HistoryResponse: {
            /** Runs */
            runs: components["schemas"]["HistoryRun"][];
            /** Total Runs */
            total_runs: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Page Size
             * @default 10
             */
            page_size: number;
        };
        /**
         * HistoryRun
         * @description Summary of a historical market run.
         */
        HistoryRun: {
            /** Run Id */
            run_id: number;
            /** Date String */
            date_string: string;
            /** Set Count */
            set_count: number;
            /** Avg Profit */
            avg_profit?: number | null;
            /** Max Profit */
            max_profit?: number | null;
        };
        /**
         * OrderbookLevel
         * @description Price level from market orderbook.
         */
        OrderbookLevel: {
            /** Platinum */
            platinum: number;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /**
         * PartDetail
         * @description Individual part information within a set.
         */
        PartDetail: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Unit Price */
            unit_price: number;
            /** Quantity */
            quantity: number;
            /** Total Cost */
            total_cost: number;
            /** Lowest Price */
            lowest_price?: number | null;
            /** Highest Bid */
            highest_bid?: number | null;
            /** Top Sell Orders */
            top_sell_orders?: components["schemas"]["OrderbookLevel"][];
            /** Top Buy Orders */
            top_buy_orders?: components["schemas"]["OrderbookLevel"][];
            /** Instant Unit Price */
            instant_unit_price?: number | null;
            /** Patient Unit Price */
            patient_unit_price?: number | null;
            /** Instant Total Cost */
            instant_total_cost?: number | null;
            /** Patient Total Cost */
            patient_total_cost?: number | null;
        };
        /**
         * RunDetailResponse
         * @description Detailed data for a specific run.
         */
        RunDetailResponse: {
            /** Run Id */
            run_id: number;
            /** Date String */
            date_string: string;
            /** Timestamp */
            timestamp: number;
            /** Sets */
            sets: {
                [key: string]: unknown;
            }[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /**
         * ScoredData
         * @description Scored profit data with normalized values and trend/volatility metrics.
         */
        ScoredData: {
            /** Set Slug */
            set_slug: string;
            /** Set Name */
            set_name: string;
            /** Set Price */
            set_price: number;
            /** Part Cost */
            part_cost: number;
            /** Profit Margin */
            profit_margin: number;
            /** Profit Percentage */
            profit_percentage: number;
            /** Instant Set Price */
            instant_set_price?: number | null;
            /** Instant Part Cost */
            instant_part_cost?: number | null;
            /** Instant Profit Margin */
            instant_profit_margin?: number | null;
            /** Instant Profit Percentage */
            instant_profit_percentage?: number | null;
            /** Patient Set Price */
            patient_set_price?: number | null;
            /** Patient Part Cost */
            patient_part_cost?: number | null;
            /** Patient Profit Margin */
            patient_profit_margin?: number | null;
            /** Patient Profit Percentage */
            patient_profit_percentage?: number | null;
            /** Part Details */
            part_details: components["schemas"]["PartDetail"][];
            /** @default instant */
            execution_mode: components["schemas"]["ExecutionMode"];
            /**
             * Volume
             * @default 0
             */
            volume: number;
            /**
             * Normalized Profit
             * @default 0
             */
            normalized_profit: number;
            /**
             * Normalized Volume
             * @default 0
             */
            normalized_volume: number;
            /**
             * Profit Score
             * @default 0
             */
            profit_score: number;
            /**
             * Volume Score
             * @default 0
             */
            volume_score: number;
            /**
             * Total Score
             * @default 0
             */
            total_score: number;
            /**
             * Trend Slope
             * @default 0
             */
            trend_slope: number;
            /**
             * Trend Multiplier
             * @default 1
             */
            trend_multiplier: number;
            /**
             * Trend Direction
             * @default stable
             */
            trend_direction: string;
            /**
             * Volatility
             * @default 0
             */
            volatility: number;
            /**
             * Volatility Penalty
             * @default 1
             */
            volatility_penalty: number;
            /**
             * Risk Level
             * @default Medium
             */
            risk_level: string;
            /**
             * Composite Score
             * @default 0
             */
            composite_score: number;
            /**
             * Profit Contribution
             * @default 0
             */
            profit_contribution: number;
            /**
             * Volume Contribution
             * @default 0
             */
            volume_contribution: number;
            /**
             * Trend Contribution
             * @default 1
             */
            trend_contribution: number;
            /**
             * Volatility Contribution
             * @default 1
             */
            volatility_contribution: number;
            /**
             * Bid Ask Ratio
             * @default 0
             */
            bid_ask_ratio: number;
            /**
             * Sell Side Competition
             * @default 0
             */
            sell_side_competition: number;
            /**
             * Liquidity Velocity
             * @default 0
             */
            liquidity_velocity: number;
            /**
             * Liquidity Multiplier
             * @default 1
             */
            liquidity_multiplier: number;
        };
        /**
         * SetDetailResponse
         * @description Detailed information for a specific set.
         */
        SetDetailResponse: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Current Price */
            current_price?: number | null;
            /** Current Profit */
            current_profit?: number | null;
            /**
             * Parts
             * @default []
             */
            parts: components["schemas"]["PartDetail"][];
            /**
             * History
             * @default []
             */
            history: components["schemas"]["SetHistoryEntry"][];
        };
        /**
         * SetHistoryEntry
         * @description Historical entry for a set.
         */
        SetHistoryEntry: {
            /** Date String */
            date_string: string;
            /** Timestamp */
            timestamp: number;
            /** Profit Margin */
            profit_margin: number;
            /** Lowest Price */
            lowest_price: number;
        };
        /**
         * SetsListResponse
         * @description Response for sets list endpoint.
         */
        SetsListResponse: {
            /** Sets */
            sets: {
                [key: string]: unknown;
            }[];
            /** Total Sets */
            total_sets: number;
            /**
             * Sort By
             * @default score
             */
            sort_by: string;
            /**
             * Order
             * @default desc
             */
            order: string;
        };
        /**
         * StatsResponse
         * @description Combined statistics response.
         */
        StatsResponse: {
            database: components["schemas"]["DatabaseStats"];
            analysis: components["schemas"]["AnalysisStats"];
        };
        /**
         * StrategyProfileResponse
         * @description Strategy profile information.
         */
        StrategyProfileResponse: {
            type: components["schemas"]["StrategyType"];
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Volatility Weight */
            volatility_weight: number;
            /** Trend Weight */
            trend_weight: number;
            /** Roi Weight */
            roi_weight: number;
            /** Min Volume Threshold */
            min_volume_threshold: number;
        };
        /**
         * StrategyType
         * @description Available trading strategy types.
         * @enum {string}
         */
        StrategyType: "safe_steady" | "balanced" | "aggressive";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WeightsConfig
         * @description Scoring weights configuration.
         */
        WeightsConfig: {
            /** @default balanced */
            strategy: components["schemas"]["StrategyType"];
            /**
             * Profit Weight
             * @default 1
             */
            profit_weight: number;
            /**
             * Volume Weight
             * @default 1.2
             */
            volume_weight: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAnalysisConfig = components['schemas']['AnalysisConfig'];
export type SchemaAnalysisResponse = components['schemas']['AnalysisResponse'];
export type SchemaAnalysisStartedResponse = components['schemas']['AnalysisStartedResponse'];
export type SchemaAnalysisStats = components['schemas']['AnalysisStats'];
export type SchemaAnalysisStatusResponse = components['schemas']['AnalysisStatusResponse'];
export type SchemaDatabaseStats = components['schemas']['DatabaseStats'];
export type SchemaExecutionMode = components['schemas']['ExecutionMode'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaHistoryResponse = components['schemas']['HistoryResponse'];
export type SchemaHistoryRun = components['schemas']['HistoryRun'];
export type SchemaOrderbookLevel = components['schemas']['OrderbookLevel'];
export type SchemaPartDetail = components['schemas']['PartDetail'];
export type SchemaRunDetailResponse = components['schemas']['RunDetailResponse'];
export type SchemaScoredData = components['schemas']['ScoredData'];
export type SchemaSetDetailResponse = components['schemas']['SetDetailResponse'];
export type SchemaSetHistoryEntry = components['schemas']['SetHistoryEntry'];
export type SchemaSetsListResponse = components['schemas']['SetsListResponse'];
export type SchemaStatsResponse = components['schemas']['StatsResponse'];
export type SchemaStrategyProfileResponse = components['schemas']['StrategyProfileResponse'];
export type SchemaStrategyType = components['schemas']['StrategyType'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaWeightsConfig = components['schemas']['WeightsConfig'];
export type $defs = Record<string, never>;
export interface operations {
    get_analysis_api_analysis_get: {
        parameters: {
            query?: {
                /** @description Force fresh data fetch */
                force_refresh?: boolean;
                /** @description Run in test mode (limited data) */
                test_mode?: boolean;
                /** @description Trading strategy (safe_steady, balanced, aggressive) */
                strategy?: string;
                /** @description Execution mode (instant, patient) */
                execution_mode?: string;
                /** @description Deprecated: Profit weight */
                profit_weight?: number;
                /** @description Deprecated: Volume weight */
                volume_weight?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_analysis_api_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalysisConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStartedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_status_api_analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatusResponse"];
                };
            };
        };
    };
    stream_analysis_progress_api_analysis_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    rescore_analysis_api_analysis_rescore_post: {
        parameters: {
            query?: {
                /** @description Trading strategy (safe_steady, balanced, aggressive) */
                strategy?: string;
                /** @description Execution mode (instant, patient) */
                execution_mode?: string;
                /** @description Deprecated */
                profit_weight?: number;
                /** @description Deprecated */
                volume_weight?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategies_api_analysis_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyProfileResponse"][];
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_history__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_analysis_api_history__run_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sets_api_sets_get: {
        parameters: {
            query?: {
                /** @description Sort field: name, profit, price */
                sort_by?: string;
                /** @description Sort order: asc or desc */
                order?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_detail_api_sets__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_history_api_sets__slug__history_get: {
        parameters: {
            query?: {
                /** @description Number of days */
                days?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    health_check_api_stats_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_data_api_export_get: {
        parameters: {
            query?: {
                /** @description Export format: json */
                format?: string;
                /** @description Include full history */
                include_history?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_to_file_api_export_file_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_summary_api_export_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}

// Compatibility aliases used by the frontend codebase.
export type StrategyType = SchemaStrategyType;
export type ExecutionMode = SchemaExecutionMode;
export type WeightsConfig = SchemaWeightsConfig;
export type StrategyProfile = SchemaStrategyProfileResponse;
export type PartDetail = SchemaPartDetail;
export type RiskLevel = "Low" | "Medium" | "High";
export type TrendDirection = "rising" | "falling" | "stable";

export type ScoredSet = Omit<SchemaScoredData, "risk_level" | "trend_direction"> & {
  risk_level: RiskLevel;
  trend_direction: TrendDirection;
  liquidity_contribution?: number;
};

export type AnalysisResponse = Omit<SchemaAnalysisResponse, "sets"> & {
  sets: ScoredSet[];
};

export type AnalysisStatus = Omit<SchemaAnalysisStatusResponse, "status"> & {
  status: "idle" | "running" | "completed" | "error";
};

export interface RescoreResponse {
  sets: ScoredSet[];
  total_sets: number;
  profitable_sets: number;
  strategy: StrategyType;
  execution_mode?: ExecutionMode;
  weights: WeightsConfig;
}

export type HistoryRun = Omit<SchemaHistoryRun, "avg_profit" | "max_profit"> & {
  avg_profit: number | null;
  max_profit: number | null;
};

export type HistoryResponse = Omit<SchemaHistoryResponse, "runs"> & {
  runs: HistoryRun[];
};

export interface RunDetail extends Omit<SchemaRunDetailResponse, "sets" | "summary"> {
  sets: Array<{
    set_slug: string;
    set_name: string;
    profit_margin: number;
    lowest_price: number;
  }>;
  summary: {
    total_sets: number;
    average_profit: number;
    max_profit: number;
    min_profit: number;
    profitable_sets: number;
  };
}

export type DatabaseStats = SchemaDatabaseStats;
export type AnalysisStats = SchemaAnalysisStats;
export type StatsResponse = SchemaStatsResponse;
export type SetHistoryEntry = SchemaSetHistoryEntry;
export type SetDetail = SchemaSetDetailResponse;
